<?php

/**
 * Generated by ZF2ModuleCreator
 */

use Infrastructure\Dao\DaoAbstractFactory;
use Infrastructure\Dao\ZendDbAwareDaoInitializer;

return [

    'view_manager' => [
        'template_path_stack' => [
            __DIR__ . '/../view',
        ],
    ],

    'service_manager' => [
        'abstract_factories' => [
            DaoAbstractFactory::class,
        ],
        'factories'          => [

        ],
        'initializers'       => [
            ZendDbAwareDaoInitializer::class,
        ],
    ],
];